version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  linux_amd64:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /home/circleci/graalvm-ce-java17-22.3.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux-amd64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc g++ zlib1g-dev
      - run:
          name: Download GraalVM
          working_directory: ~/
          command: |
            if ! [ -d graalvm-ce-java17-22.3.2 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-linux-amd64-22.3.2.tar.gz
              tar xzf graalvm-ce-java17-linux-amd64-22.3.2.tar.gz
            fi
      - run:
          name: Install GraalVM native-image
          working_directory: ~/graalvm-ce-java17-22.3.2
          command: bin/gu install native-image
      - run:
          name: Compile native image
          working_directory: ~/repo/cljfmt
          command: lein native-image
      - store_artifacts:
          path: cljfmt/target/cljfmt
          destination: cljfmt
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java17-22.3.2
          key: linux-amd64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
  linux_aarch64:
    machine:
      enabled: true
      image: ubuntu-2004:2022.04.2
    resource_class: arm.medium
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /home/circleci/graalvm-ce-java17-22.3.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux-aarch64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Download Leiningen
          working_directory: ~/
          command: |
            wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
            chmod +x lein
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc g++ zlib1g-dev
      - run:
          name: Download GraalVM
          working_directory: ~/
          command: |
            if ! [ -d graalvm-ce-java17-22.3.2 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-linux-aarch64-22.3.2.tar.gz
              tar xzf graalvm-ce-java17-linux-aarch64-22.3.2.tar.gz
            fi
      - run:
          name: Install GraalVM native-image
          working_directory: ~/graalvm-ce-java17-22.3.2
          command: bin/gu install native-image
      - run:
          name: Compile native image
          working_directory: ~/repo/cljfmt
          command: ~/lein native-image
      - store_artifacts:
          path: cljfmt/target/cljfmt
          destination: cljfmt
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java17-22.3.2
          key: linux-aarch64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
  macos_amd64:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /Users/distiller/graalvm-ce-java17-22.3.2/Contents/Home
    steps:
      - checkout
      - restore_cache:
          keys:
            - macos-amd64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Download Leiningen
          working_directory: ~/
          command: |
            curl -O -sL https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
            chmod +x lein
      - run:
          name: Download GraalVM
          working_directory: ~/
          command: |
            if ! [ -d graalvm-ce-java17-22.3.2 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-darwin-amd64-22.3.2.tar.gz
              tar xzf graalvm-ce-java17-darwin-amd64-22.3.2.tar.gz
            fi
      - run:
          name: Install GraalVM native-image
          working_directory: ~/graalvm-ce-java17-22.3.2/Contents/Home
          command: bin/gu install native-image
      - run:
          name: Compile native image
          working_directory: ~/repo/cljfmt
          command: ~/lein native-image
      - store_artifacts:
          path: cljfmt/target/cljfmt
          destination: cljfmt
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java17-22.3.2
          key: macos-amd64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
  macos_aarch64:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /Users/distiller/graalvm-ce-java17-22.3.1/Contents/Home
    steps:
      - checkout
      - restore_cache:
          keys:
            - macos-aarch64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Download Leiningen
          working_directory: ~/
          command: |
            curl -O -sL https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
            chmod +x lein
      - run:
          name: Download GraalVM
          working_directory: ~/
          command: |
            if ! [ -d graalvm-ce-java17-22.3.1 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-darwin-aarch64-22.3.1.tar.gz
              tar xzf graalvm-ce-java17-darwin-aarch64-22.3.1.tar.gz
            fi
      - run:
          name: Install GraalVM native-image
          working_directory: ~/graalvm-ce-java17-22.3.1/Contents/Home
          command: bin/gu install native-image
      - run:
          name: Compile native image
          working_directory: ~/repo/cljfmt
          command: ~/lein native-image
      - store_artifacts:
          path: cljfmt/target/cljfmt
          destination: cljfmt
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java17-22.3.1
          key: macos-aarch64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
  windows:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - win-amd64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Download Leiningen
          shell: powershell.exe
          command: |
            (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat', 'lein.bat')
      - run:
          name: Install Leiningen
          command: .\lein self-install
      - run:
          name: Download GraalVM
          shell: powershell.exe
          command: |
            if (Test-Path('graalvm')) {
              return
            } else {
              (New-Object Net.WebClient).DownloadFile('https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-windows-amd64-22.3.2.zip', 'graalvm.zip')
              Expand-Archive graalvm.zip graalvm
            }
      - run:
          name: Install GraalVM native image
          working_directory: graalvm/graalvm-ce-java17-22.3.2
          command: bin\gu install native-image
      - run:
          name: Compile native image
          working_directory: cljfmt
          command: |
            set GRAALVM_HOME=%CIRCLE_WORKING_DIRECTORY%\graalvm\graalvm-ce-java17-22.3.2 & set PATH=%PATH%;%GRAALVM_HOME%\bin & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" & ..\lein native-image
      - store_artifacts:
          path: cljfmt/target/cljfmt
          destination: cljfmt
      - save_cache:
          paths:
            - .m2
            - graalvm
          key: win-amd64-{{ checksum "deps.edn" }}-{{ checksum ".circleci/config.yml" }}
workflows:
  compile:
    jobs:
      - windows
